/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import com.sun.imageio.plugins.jpeg.JPEG;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuBar;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author JHONCII
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        //Para bloquear el maximizar
        this.setResizable(false);
    }

    //Llamar Inicio
    public void llamarInicio() {
        Inicio ventanaInicio = new Inicio();
        jdspPanel.removeAll();
        jdspPanel.add(ventanaInicio);
        ventanaInicio.show();
        jdspPanel.setVisible(true);
    }

    //LLamarRegistroAlimento
    public void llamarRegistroAlimento() {
        RegistroAlimentos ventanaAlimento = new RegistroAlimentos();
        jdspPanel.removeAll();
        jdspPanel.add(ventanaAlimento);
        ventanaAlimento.show();
        jdspPanel.setVisible(true);
    }

    public void llamarRegistroUsuarios() {
        RegistroUsuario ventanaUsuarios=new RegistroUsuario();
        jdspPanel.removeAll();
        jdspPanel.add(ventanaUsuarios);
        ventanaUsuarios.show();
        jdspPanel.setVisible(true);
    }
    //Limpiar el Panel 

    public void limpiarPanel() {
        jdspPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jdspPanel = new javax.swing.JDesktopPane();
        jtxtParametro = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        jmnuInicio = new javax.swing.JMenu();
        jmnuAdministrar = new javax.swing.JMenu();
        jmnuEstudiantes = new javax.swing.JMenu();
        jmnuUsuarios = new javax.swing.JMenu();
        jmnuReportes = new javax.swing.JMenu();
        jmnuGeneral = new javax.swing.JMenu();
        jmnuTipo = new javax.swing.JMenu();
        jmnuGrafico = new javax.swing.JMenu();
        jmnuSalir = new javax.swing.JMenu();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTRO ESTUDIANTES");
        setName("jframeRegistro"); // NOI18N

        jdspPanel.setPreferredSize(new java.awt.Dimension(1000, 700));

        jdspPanel.setLayer(jtxtParametro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdspPanelLayout = new javax.swing.GroupLayout(jdspPanel);
        jdspPanel.setLayout(jdspPanelLayout);
        jdspPanelLayout.setHorizontalGroup(
            jdspPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdspPanelLayout.createSequentialGroup()
                .addContainerGap(641, Short.MAX_VALUE)
                .addComponent(jtxtParametro, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(276, 276, 276))
        );
        jdspPanelLayout.setVerticalGroup(
            jdspPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdspPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxtParametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(635, Short.MAX_VALUE))
        );

        jTextField1.setText("jTextField1");

        jmnuInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/JP_INICIO.png"))); // NOI18N
        jmnuInicio.setText("  INICIO    ");
        jmnuInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmnuInicioMouseClicked(evt);
            }
        });
        jMenuBar2.add(jmnuInicio);

        jmnuAdministrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/JP_ADMINISTRAR.png"))); // NOI18N
        jmnuAdministrar.setText("ADMINISTRAR   ");
        jmnuAdministrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmnuAdministrarMouseClicked(evt);
            }
        });

        jmnuEstudiantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/JP_ALIMENTOS (1).png"))); // NOI18N
        jmnuEstudiantes.setText("REGISTRO ALIMENTOS");
        jmnuEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmnuEstudiantesMouseClicked(evt);
            }
        });
        jmnuAdministrar.add(jmnuEstudiantes);

        jmnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/JP_USUARIOS.png"))); // NOI18N
        jmnuUsuarios.setText("USUARIOS");
        jmnuUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmnuUsuariosMouseClicked(evt);
            }
        });
        jmnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuUsuariosActionPerformed(evt);
            }
        });
        jmnuAdministrar.add(jmnuUsuarios);

        jMenuBar2.add(jmnuAdministrar);

        jmnuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/JP_REPORTES.png"))); // NOI18N
        jmnuReportes.setText("REPORTES    ");
        jmnuReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmnuReportesMouseClicked(evt);
            }
        });

        jmnuGeneral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/JP_GENERAL.png"))); // NOI18N
        jmnuGeneral.setText("GENERAL");
        jmnuGeneral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmnuGeneralMouseClicked(evt);
            }
        });
        jmnuReportes.add(jmnuGeneral);

        jmnuTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/JP_PORCEDULA.png"))); // NOI18N
        jmnuTipo.setText("ALIMENTOS POR TIPO");
        jmnuTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmnuTipoMouseClicked(evt);
            }
        });
        jmnuReportes.add(jmnuTipo);

        jmnuGrafico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/JP_GRAFICO.png"))); // NOI18N
        jmnuGrafico.setText("GRÁFICO    ");
        jmnuGrafico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmnuGraficoMouseClicked(evt);
            }
        });
        jmnuGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuGraficoActionPerformed(evt);
            }
        });
        jmnuReportes.add(jmnuGrafico);

        jMenuBar2.add(jmnuReportes);

        jmnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/JP_SALIR.png"))); // NOI18N
        jmnuSalir.setText("  SALIR");
        jmnuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmnuSalirMouseClicked(evt);
            }
        });
        jmnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuSalirActionPerformed(evt);
            }
        });
        jMenuBar2.add(jmnuSalir);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdspPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdspPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmnuSalirActionPerformed

    private void jmnuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmnuSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jmnuSalirMouseClicked

    private void jmnuInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmnuInicioMouseClicked
        
        llamarInicio();
    }//GEN-LAST:event_jmnuInicioMouseClicked

    private void jmnuEstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmnuEstudiantesMouseClicked
        limpiarPanel();
        llamarRegistroAlimento();

    }//GEN-LAST:event_jmnuEstudiantesMouseClicked


    private void jmnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuUsuariosActionPerformed
    }//GEN-LAST:event_jmnuUsuariosActionPerformed

    private void jmnuGeneralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmnuGeneralMouseClicked
    try {
            Conexion cc = new Conexion();
            Connection cn = cc.conectar();
            JasperReport reporte = JasperCompileManager.compileReport("C:\\Users\\Cargua\\Desktop\\Universidad\\universidad\\ProyectoAgiles\\src\\Reportes\\reporteListadoAlimentos.jrxml");
            JasperPrint impresion = JasperFillManager.fillReport(reporte, null, cn);
            JasperViewer.viewReport(impresion, false);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "Reporte no esta disponible, counicate con administracion");
        }

    }//GEN-LAST:event_jmnuGeneralMouseClicked

    private void jmnuUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmnuUsuariosMouseClicked
        limpiarPanel();
        llamarRegistroUsuarios();

    }//GEN-LAST:event_jmnuUsuariosMouseClicked

    private void jmnuAdministrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmnuAdministrarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jmnuAdministrarMouseClicked

    private void jmnuReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmnuReportesMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_jmnuReportesMouseClicked

    private void jmnuTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmnuTipoMouseClicked
         try {
            Conexion cc = new Conexion();
            Connection cn = cc.conectar();
            Map parametro = new HashMap();
             parametro.put("TipoAlimento", jtxtParametro.getText());
            JasperReport reporte = JasperCompileManager.compileReport("C:\\Users\\Cargua\\Desktop\\Universidad\\universidad\\ProyectoAgiles\\src\\Reportes\\reportextip.jrxml");
            JasperPrint impresion = JasperFillManager.fillReport(reporte, parametro,cn);
            JasperViewer.viewReport(impresion, false);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "El reporte no esta disponible comunicate con el administrador");
        }
    }//GEN-LAST:event_jmnuTipoMouseClicked

    private void jmnuGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuGraficoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jmnuGraficoActionPerformed

    private void jmnuGraficoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmnuGraficoMouseClicked
       try {
            Conexion cc = new Conexion();
            Connection cn = cc.conectar();
            Map parametros = new HashMap();
            JasperReport reporte = JasperCompileManager.compileReport("C:\\Users\\Cargua\\Desktop\\Universidad\\universidad\\ProyectoAgiles\\src\\Reportes\\reporteAlimentos.jrxml");
            JasperPrint impresion = JasperFillManager.fillReport(reporte, null, cn);
            JasperViewer.viewReport(impresion, false);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "El reporte no esta disponible comunicate con administrador");
        }
    }//GEN-LAST:event_jmnuGraficoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JDesktopPane jdspPanel;
    private javax.swing.JMenu jmnuAdministrar;
    private javax.swing.JMenu jmnuEstudiantes;
    private javax.swing.JMenu jmnuGeneral;
    private javax.swing.JMenu jmnuGrafico;
    private javax.swing.JMenu jmnuInicio;
    private javax.swing.JMenu jmnuReportes;
    private javax.swing.JMenu jmnuSalir;
    private javax.swing.JMenu jmnuTipo;
    private javax.swing.JMenu jmnuUsuarios;
    private javax.swing.JTextField jtxtParametro;
    // End of variables declaration//GEN-END:variables
}
